/*******************************************************************************
* File Name   : usbd_ac_config.c
*
* Description : USB Audio Class (USBD_AC) descriptor configuration data.
*               Generated by SEGGER emUSBD Audio Device Generator tool V1.01,
*               adapted for the PSoC Edge KIT_PSE84_EVAL_EPC2 audio device.
*
*               Device topology (sample rate follows AUDIO_SAMPLE_FREQ in
*               proj_cm55/include/audio.h; descriptors are parameterized):
*                 Speaker:    mono,   16-bit, asynchronous + feedback EP
*                 Microphone: stereo, 16-bit, synchronous
*
*******************************************************************************
* (c) 2025-2026, Infineon Technologies AG, or an affiliate of Infineon
* Technologies AG. All rights reserved.
* This software, associated documentation and materials ("Software") is
* owned by Infineon Technologies AG or one of its affiliates ("Infineon")
* and is protected by and subject to worldwide patent protection, worldwide
* copyright laws, and international treaty provisions. Therefore, you may use
* this Software only as provided in the license agreement accompanying the
* software package from which you obtained this Software. If no license
* agreement applies, then any use, reproduction, modification, translation, or
* compilation of this Software is prohibited without the express written
* permission of Infineon.
*
* Disclaimer: UNLESS OTHERWISE EXPRESSLY AGREED WITH INFINEON, THIS SOFTWARE
* IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
* INCLUDING, BUT NOT LIMITED TO, ALL WARRANTIES OF NON-INFRINGEMENT OF
* THIRD-PARTY RIGHTS AND IMPLIED WARRANTIES SUCH AS WARRANTIES OF FITNESS FOR A
* SPECIFIC USE/PURPOSE OR MERCHANTABILITY.
* Infineon reserves the right to make changes to the Software without notice.
* You are responsible for properly designing, programming, and testing the
* functionality and safety of your intended application of the Software, as
* well as complying with any legal requirements related to its use. Infineon
* does not guarantee that the Software will be free from intrusion, data theft
* or loss, or other breaches ("Security Breaches"), and Infineon shall have
* no liability arising out of any Security Breaches. Unless otherwise
* explicitly approved by Infineon, the Software may not be used in any
* application where a failure of the Product or any consequences of the use
* thereof can reasonably be expected to result in personal injury.
*******************************************************************************/

#include "USB_AC.h"
#include "usbd_ac_config.h"
#include "audio.h"

#if USBD_AC_GENERATOR_FORMAT != 1
  #error "Incompatible USBD_AC data structures"
#endif

/* Expand a value into 3 little-endian bytes for the USB Audio 24-bit
 * tSamFreq field. Keeps the advertised sample rate in lock-step with
 * AUDIO_SAMPLE_FREQ so the host streams at the rate the device hardware
 * actually produces/consumes. */
#define USBD_AC_SAMFREQ_3B(freq)   ((freq) & 0xFFU), \
                                   (((freq) >> 8) & 0xFFU), \
                                   (((freq) >> 16) & 0xFFU)

/* ========================================================================== */
/*  Class-Specific AC Interface Descriptor (Audio Control)                    */
/* ========================================================================== */
static const U8 _ControlDesc[] = {
  /* Class-Specific AC Interface Header Descriptor */
  0x0a,                      /* bLength */
  0x24,                      /* bDescriptorType */
  0x01,                      /* bDescriptorSubtype */
  0x00, 0x01,                /* bcdADC */
  0x47, 0x00,                /* wTotalLength */
  0x02,                      /* bInCollection */
  0x00,                      /* baInterfaceNr */
  0x00,
  /* Input Terminal Descriptor */
  0x0c,                      /* bLength */
  0x24,                      /* bDescriptorType */
  0x02,                      /* bDescriptorSubtype */
  0x01,                      /* bTerminalID */
  0x01, 0x01,                /* wTerminalType */
  0x00,                      /* bAssocTerminal */
  0x01,                      /* bNrChannels */
  0x01, 0x00,                /* bmChannelConfig */
  0x00,                      /* iChannelNames */
  0x00,                      /* iTerminal */
  /* Feature Unit Descriptor */
  0x09,                      /* bLength */
  0x24,                      /* bDescriptorType */
  0x06,                      /* bDescriptorSubtype */
  0x02,                      /* bUnitID */
  0x01,                      /* bSourceID */
  0x01,                      /* bControlSize */
  0x03,                      /* bmaControls */
  0x00,
  0x00,                      /* iFeature */
  /* Output Terminal Descriptor */
  0x09,                      /* bLength */
  0x24,                      /* bDescriptorType */
  0x03,                      /* bDescriptorSubtype */
  0x03,                      /* bTerminalID */
  0x01, 0x03,                /* wTerminalType */
  0x00,                      /* bAssocTerminal */
  0x02,                      /* bSourceID */
  0x10,                      /* iTerminal */
  /* Input Terminal Descriptor */
  0x0c,                      /* bLength */
  0x24,                      /* bDescriptorType */
  0x02,                      /* bDescriptorSubtype */
  0x04,                      /* bTerminalID */
  0x01, 0x02,                /* wTerminalType */
  0x00,                      /* bAssocTerminal */
  0x02,                      /* bNrChannels */
  0x03, 0x00,                /* bmChannelConfig */
  0x00,                      /* iChannelNames */
  0x11,                      /* iTerminal */
  /* Feature Unit Descriptor */
  0x0a,                      /* bLength */
  0x24,                      /* bDescriptorType */
  0x06,                      /* bDescriptorSubtype */
  0x05,                      /* bUnitID */
  0x04,                      /* bSourceID */
  0x01,                      /* bControlSize */
  0x03,                      /* bmaControls */
  0x00,
  0x00,
  0x00,                      /* iFeature */
  /* Output Terminal Descriptor */
  0x09,                      /* bLength */
  0x24,                      /* bDescriptorType */
  0x03,                      /* bDescriptorSubtype */
  0x06,                      /* bTerminalID */
  0x01, 0x01,                /* wTerminalType */
  0x00,                      /* bAssocTerminal */
  0x05,                      /* bSourceID */
  0x00                       /* iTerminal */
};

/* Class-Specific AS Interface Descriptor (Speaker) */
static const U8 _StreamDesc_0_1[] = {
  /* Class-Specific AS Interface Header Descriptor */
  0x07,                      /* bLength */
  0x24,                      /* bDescriptorType */
  0x01,                      /* bDescriptorSubtype */
  0x01,                      /* bTerminalLink */
  0x00,                      /* bDelay */
  0x01, 0x00,                /* wFormatTag */
  /* Type I Format Type Descriptor */
  0x0b,                      /* bLength */
  0x24,                      /* bDescriptorType */
  0x02,                      /* bDescriptorSubtype */
  0x01,                      /* bFormatType */
  0x01,                      /* bNrChannels */
  0x02,                      /* bSubframeSize */
  0x10,                      /* bBitResolution */
  0x01,                      /* bSamFreqType */
  USBD_AC_SAMFREQ_3B(AUDIO_OUT_SAMPLE_FREQ)  /* tSamFreq (tracks AUDIO_OUT_SAMPLE_FREQ) */
};

/* Class-Specific AS Isochronous Audio Data Endpoint Descriptor (Speaker) */
static const U8 _StreamEPDesc_0_1[] = {
  0x07,                      /* bLength */
  0x25,                      /* bDescriptorType */
  0x01,                      /* bDescriptorSubtype */
  0x01,                      /* bmAttributes */
  0x00,                      /* bLockDelayUnits */
  0x00, 0x00                 /* wLockDelay */
};

/* Class-Specific AS Interface Descriptor (Microphone) */
static const U8 _StreamDesc_1_1[] = {
  /* Class-Specific AS Interface Header Descriptor */
  0x07,                      /* bLength */
  0x24,                      /* bDescriptorType */
  0x01,                      /* bDescriptorSubtype */
  0x06,                      /* bTerminalLink */
  0x00,                      /* bDelay */
  0x01, 0x00,                /* wFormatTag */
  /* Type I Format Type Descriptor */
  0x0b,                      /* bLength */
  0x24,                      /* bDescriptorType */
  0x02,                      /* bDescriptorSubtype */
  0x01,                      /* bFormatType */
  0x02,                      /* bNrChannels */
  0x02,                      /* bSubframeSize */
  0x10,                      /* bBitResolution */
  0x01,                      /* bSamFreqType */
  USBD_AC_SAMFREQ_3B(AUDIO_IN_SAMPLE_FREQ)   /* tSamFreq (tracks AUDIO_IN_SAMPLE_FREQ) */
};

/* Class-Specific AS Isochronous Audio Data Endpoint Descriptor (Microphone) */
static const U8 _StreamEPDesc_1_1[] = {
  0x07,                      /* bLength */
  0x25,                      /* bDescriptorType */
  0x01,                      /* bDescriptorSubtype */
  0x01,                      /* bmAttributes */
  0x00,                      /* bLockDelayUnits */
  0x00, 0x00                 /* wLockDelay */
};

/* String table */
static const char * const _Strings[] = {
  "Speaker",
  "Microphone",
  "Audio Speaker",
  "Audio Microphone"
};

/*
 * Endpoint table (packet sizes derived from AUDIO_SAMPLE_FREQ via audio.h):
 * EP0: Speaker OUT - async ISO, MaxPkt = nominal + feedback headroom, interval=8 uframes (1ms)
 * EP1: Feedback IN - explicit feedback, 4B, interval=8 uframes (1ms), matching the speaker data EP
 * EP2: Microphone IN - sync ISO, MaxPkt = nominal + drift headroom, interval=8 uframes (1ms)
 */
static const USBD_AC_EP_INFO _Endpoints[] = {
  {  1, 0, {   MAX_AUDIO_OUT_EP_PACKET_SIZE_BYTES,    8, USB_ADD_EP_FLAG_USE_ISO_SYNC_TYPES, USB_DIR_OUT, USB_TRANSFER_TYPE_ISO,  USB_ISO_SYNC_TYPE_ASYNCHRONOUS }},
  {  1, 0, {     4,    8, USB_ADD_EP_FLAG_USE_ISO_SYNC_TYPES, USB_DIR_IN,  USB_TRANSFER_TYPE_ISO,  USB_ISO_SYNC_TYPE_EXP_FEEDBACK }},
  {  2, 0, {   MAX_AUDIO_IN_EP_PACKET_SIZE_BYTES,    8, USB_ADD_EP_FLAG_USE_ISO_SYNC_TYPES, USB_DIR_IN,  USB_TRANSFER_TYPE_ISO,  USB_ISO_SYNC_TYPE_SYNCHRONOUS }}
};

/* Interface info for interface 'Speaker' */
static const USBD_AC_INTF_INFO _Interface_0[] = {
  {            /* Alt setting 0 */
      18,      /* String index */
      -1,      /* Data EP index */
      -1,      /* Feedback EP index */
    0,
    NULL,
    NULL,
    0,
    {
       0,      /* MaxPacketSize */
       0,      /* IntervalExp */
       0,      /* NrChannels */
       0,      /* SubframeSize */
       0       /* BitResolution */
    }
  },
  {            /* Alt setting 1 */
      18,      /* String index */
       0,      /* Data EP index */
       1,      /* Feedback EP index */
    sizeof(_StreamEPDesc_0_1),
    _StreamEPDesc_0_1,
    _StreamDesc_0_1,
    sizeof(_StreamDesc_0_1),
    {
     MAX_AUDIO_OUT_EP_PACKET_SIZE_BYTES,  /* MaxPacketSize (nominal + feedback headroom) */
       3,      /* IntervalExp */
       1,      /* NrChannels */
       2,      /* SubframeSize */
      16       /* BitResolution */
    }
  }
};

/* Interface info for interface 'Microphone' */
static const USBD_AC_INTF_INFO _Interface_1[] = {
  {            /* Alt setting 0 */
      19,      /* String index */
      -1,      /* Data EP index */
      -1,      /* Feedback EP index */
    0,
    NULL,
    NULL,
    0,
    {
       0,      /* MaxPacketSize */
       0,      /* IntervalExp */
       0,      /* NrChannels */
       0,      /* SubframeSize */
       0       /* BitResolution */
    }
  },
  {            /* Alt setting 1 */
      19,      /* String index */
       2,      /* Data EP index */
      -1,      /* Feedback EP index */
    sizeof(_StreamEPDesc_1_1),
    _StreamEPDesc_1_1,
    _StreamDesc_1_1,
    sizeof(_StreamDesc_1_1),
    {
     MAX_AUDIO_IN_EP_PACKET_SIZE_BYTES,  /* MaxPacketSize (nominal + drift headroom) */
       3,      /* IntervalExp */
       2,      /* NrChannels */
       2,      /* SubframeSize */
      16       /* BitResolution */
    }
  }
};

/* Interface list */
static const USBD_AC_INTF_LIST _InterfaceList[] = {
  { 2, 0, _Interface_0 },
  { 2, 1, _Interface_1 }
};

/* Configuration for 'audio' */
extern const USBD_AC_CONFIG USB_AC_Config_audio;

const USBD_AC_CONFIG USB_AC_Config_audio = {
   1,        /* Generator major version */
   0,        /* USB audio protocol version */
   2,        /* Number of streaming interfaces */
   3,        /* Number of endpoints */
  16,        /* Index of first string in string table */
   4,        /* Number of strings in string table */
   0,        /* String index for control interface. */
  sizeof(_ControlDesc),
  _ControlDesc,              /* Control interface descriptor */
  _InterfaceList,            /* Streaming interfaces */
  _Endpoints,                /* Endpoint list */
  _Strings                   /* String descriptors */
};
